[project]
name = "tip-hexadecimal-package"
authors = ["Hex Token Developers"]
description = "A comprehensive digital asset tokenization platform on Stacks"
telemetry = false
requirements = []
[contracts.hex-token-vault]
path = "contracts/hex-token-vault.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
